//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siteSPPP_proto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTICIAS
    {
        public System.DateTime FECHA { get; set; }
        public string EVENTO { get; set; }
        public string TITULO { get; set; }
        public string ENCABEZADO { get; set; }
        public System.DateTime FECHA_PUBLICACION { get; set; }
        public string RESPONSABLE { get; set; }
        public string EVENTO2 { get; set; }
        public string BALAZO1 { get; set; }
        public short ID_NOTICIA { get; set; }
        public Nullable<short> ID_FOTO { get; set; }
        public string VER_COPLADENAY { get; set; }
        public string VER_SEPLAN { get; set; }
        public string VER_COCYTEN { get; set; }
        public string VER_FOMIX { get; set; }
        public string VER_INTRANET { get; set; }
        public string BALAZO2 { get; set; }
        public string BALAZO3 { get; set; }
        public string LUGAR { get; set; }
        public Nullable<byte> PRIORIDAD { get; set; }
        public string EVENTO3 { get; set; }
        public string SOLO_MEDIOS { get; set; }
        public string PARTICIPANTES { get; set; }
        public string RESENIA { get; set; }
        public string VER_DIF { get; set; }
        public string USUARIO { get; set; }
        public string EVENTO4 { get; set; }
        public byte[] FOTO_PRINCIPAL { get; set; }
        public string PIE_FOTO_PRINCIPAL { get; set; }
        public byte[] FOTO_2 { get; set; }
        public string PIE_FOTO_2 { get; set; }
        public byte[] FOTO_3 { get; set; }
        public string PIE_FOTO_3 { get; set; }
        public byte[] FOTO_4 { get; set; }
        public string PIE_FOTO_4 { get; set; }
        public byte[] FOTO_5 { get; set; }
        public string PIE_FOTO_5 { get; set; }
        public byte[] FOTO_6 { get; set; }
        public string PIE_FOTO_6 { get; set; }
        public byte[] FOTO_7 { get; set; }
        public string PIE_FOTO_7 { get; set; }
        public byte[] FOTO_8 { get; set; }
        public string PIE_FOTO_8 { get; set; }
        public byte[] FOTO_9 { get; set; }
        public string PIE_FOTO_9 { get; set; }
        public byte[] FOTO_10 { get; set; }
        public string PIE_FOTO_10 { get; set; }
    }
}
